### ISSUE TITLE
TODO list for game sellings

### ISSUE THREAD

**Issue by andredarcie** [open-video-game-data/home#3]
General
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_video_game_franchises
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_game_consoles
- [ ] https://en.wikipedia.org/wiki/List_of_most-played_video_games_by_player_count

Microsoft
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Xbox_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Xbox_360_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Xbox_One_video_games

Sony
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_PlayStation_1_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_PlayStation_2_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_PlayStation_3_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_PlayStation_4_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_PlayStation_5_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_PSP_video_games

Nintendo
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Nintendo_Entertainment_System_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Super_Nintendo_Entertainment_System_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Nintendo_64_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_GameCube_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Wii_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Wii_U_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Nintendo_Switch_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Game_Boy_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Game_Boy_Advance_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Nintendo_DS_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Nintendo_3DS_video_games

Others
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Atari_2600_video_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_PC_games
- [ ] https://en.wikipedia.org/wiki/List_of_best-selling_Sega_Genesis_games
